import { Candidate, JobListing, Interview, MessageThread, NotificationItem, CompanyProfile } from './types';

export const INITIAL_JOBS: JobListing[] = [
  {
    id: 'job-1',
    title: 'Senior Product Designer',
    department: 'Design',
    openings: 2,
    employmentType: 'Full-time',
    description: 'We are seeking an experienced Senior Product Designer to lead design systems and candidate workflow experience across web and mobile platforms.',
    responsibilities: 'Lead end-to-end design sprints\nMaintain design system components in Figma\nCollaborate closely with engineering and product managers\nConduct user testing with recruiting leaders',
    requiredExperience: '5+ years in product design for SaaS',
    education: "Bachelor's degree in Design, HCI or equivalent",
    skills: 'Figma, Design Systems, Prototyping, User Research',
    salaryRange: '₹14,00,000 – ₹22,00,000',
    salaryType: 'Annual',
    benefits: 'Comprehensive medical insurance, ₹50,000 annual learning stipend, remote equipment budget',
    incentives: 'ESOP equity options, annual performance bonus up to 15%',
    country: 'India',
    state: 'Madhya Pradesh',
    city: 'Bhopal',
    area: 'Arera Colony',
    workMode: 'Hybrid',
    preferredSkills: 'Design tokens, Motion design, Tailwind CSS understanding',
    availability: 'Within 30 days',
    status: 'active',
    postedDate: '3 days ago',
    applicantsCount: 64,
    shortlistedCount: 12,
  },
  {
    id: 'job-2',
    title: 'Backend Engineer (Node.js & Go)',
    department: 'Engineering',
    openings: 3,
    employmentType: 'Full-time',
    description: 'Scale our real-time matching algorithm and candidate verification infrastructure handling millions of daily queries.',
    responsibilities: 'Architect high-throughput microservices\nOptimize PostgreSQL and Redis caching layers\nBuild reliable background job workers and webhook delivery',
    requiredExperience: '4+ years backend systems experience',
    education: 'B.Tech / B.E in Computer Science or related',
    skills: 'Node.js, TypeScript, PostgreSQL, Redis, Docker, Go',
    salaryRange: '₹18,00,000 – ₹28,00,000',
    salaryType: 'Annual',
    benefits: 'Full health coverage, flexible PTO, home office setup',
    incentives: 'Retention bonus, quarterly stock grants',
    country: 'India',
    state: 'Karnataka',
    city: 'Bengaluru',
    area: 'Indiranagar',
    workMode: 'Remote',
    preferredSkills: 'Kubernetes, AWS Cloud architecture, Kafka',
    availability: 'Immediate',
    status: 'active',
    postedDate: '1 week ago',
    applicantsCount: 118,
    shortlistedCount: 20,
  },
  {
    id: 'job-3',
    title: 'Growth Marketing Lead',
    department: 'Marketing',
    openings: 1,
    employmentType: 'Full-time',
    description: 'Drive employer acquisition and inbound qualified recruitment leads through performance marketing and content engines.',
    responsibilities: 'Oversee multi-channel acquisition funnels\nManage paid advertising budgets across Google and LinkedIn\nRun conversion rate optimization experiments',
    requiredExperience: '4+ years B2B growth marketing',
    education: "Bachelor's degree in Marketing, Business, or Communications",
    skills: 'B2B Growth, Paid Media, Google Analytics, SEO, CRO',
    salaryRange: '₹12,00,000 – ₹18,00,000',
    salaryType: 'Annual',
    benefits: 'Health insurance, annual tech allowance',
    incentives: 'Performance-based milestone bonuses',
    country: 'India',
    state: 'Madhya Pradesh',
    city: 'Indore',
    area: 'Vijay Nagar',
    workMode: 'On-site',
    preferredSkills: 'HubSpot, Mixpanel, Account-Based Marketing',
    availability: 'Within 30 days',
    status: 'paused',
    postedDate: '2 weeks ago',
    applicantsCount: 41,
    shortlistedCount: 6,
  },
  {
    id: 'job-4',
    title: 'QA Automation Engineer',
    department: 'Engineering',
    openings: 2,
    employmentType: 'Full-time',
    description: 'Own test automation suites for candidate workflows, verification microservices, and end-to-end recruiter dashboards.',
    responsibilities: 'Write robust Playwright and Cypress test suites\nIntegrate automated regression runs into GitHub Actions CI\nPartner with developers to prevent regressions',
    requiredExperience: '3+ years QA automation',
    education: 'B.Tech / BCA or equivalent degree',
    skills: 'Playwright, Cypress, TypeScript, Jest, CI/CD',
    salaryRange: '₹10,00,000 – ₹15,00,000',
    salaryType: 'Annual',
    benefits: 'Group medical cover, remote allowances',
    incentives: 'Annual appraisal incentives',
    country: 'India',
    state: 'Maharashtra',
    city: 'Pune',
    area: 'Baner',
    workMode: 'Hybrid',
    preferredSkills: 'Load testing with k6, API contract testing',
    availability: 'Immediate',
    status: 'draft',
    postedDate: 'Draft',
    applicantsCount: 0,
    shortlistedCount: 0,
  },
  {
    id: 'job-5',
    title: 'Senior DevOps / SRE Specialist',
    department: 'Infrastructure',
    openings: 1,
    employmentType: 'Full-time',
    description: 'Maintain 99.99% uptime, security isolation, and CI/CD pipelines for our cloud deployment clusters.',
    responsibilities: 'Manage AWS Terraform configurations\nMonitor telemetry using Prometheus and Grafana\nLead disaster recovery simulations and security audits',
    requiredExperience: '5+ years SRE / DevOps practice',
    education: "Bachelor's degree in Technology / IT",
    skills: 'Kubernetes, Terraform, AWS, Prometheus, CI/CD',
    salaryRange: '₹22,00,000 – ₹32,00,000',
    salaryType: 'Annual',
    benefits: 'Comprehensive wellness package, home lab stipend',
    incentives: 'Annual equity refreshment',
    country: 'India',
    state: 'Karnataka',
    city: 'Bengaluru',
    area: 'Koramangala',
    workMode: 'Remote',
    preferredSkills: 'SOC2 compliance, Zero Trust architecture',
    availability: 'Within 60 days',
    status: 'closed',
    postedDate: '1 month ago',
    applicantsCount: 87,
    shortlistedCount: 9,
  },
];

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: 'cand-1',
    name: 'Maya Chen',
    role: 'Senior Product Designer',
    department: 'Design',
    location: 'Bhopal, MP',
    experienceYears: 6,
    skills: ['Figma', 'Design Systems', 'Prototyping', 'User Research', 'Tokens'],
    matchScore: 94,
    salaryExpected: '₹18,00,000',
    avatarBg: '#42326E',
    bio: 'Lead product designer passionate about clean design systems, recruiting workflows, and high-conversion enterprise interfaces.',
    appliedDate: '2 hours ago',
    currentCompany: 'Aura Interactive',
    previousCompanies: ['Freshworks', 'Zomato Design Lab'],
    education: 'B.Des, National Institute of Design (NID)',
    phone: '+91 98260 41120',
    email: 'maya.chen@example.com',
    stage: 'Shortlisted',
    bookmarked: true,
    verified: {
      identity: true,
      phone: true,
      email: true,
      experience: true,
      education: true,
    },
    notes: ['Exceptional portfolio on complex dashboard systems', 'Available for interviews next Tuesday'],
  },
  {
    id: 'cand-2',
    name: 'Arjun Rao',
    role: 'Senior Backend Engineer',
    department: 'Engineering',
    location: 'Bengaluru, KA',
    experienceYears: 5,
    skills: ['Node.js', 'PostgreSQL', 'Redis', 'Docker', 'Go', 'GraphQL'],
    matchScore: 92,
    salaryExpected: '₹24,00,000',
    avatarBg: '#B9812C',
    bio: 'Distributed systems builder focused on low-latency microservices, async message buses, and relational database schema design.',
    appliedDate: '1 day ago',
    currentCompany: 'HyperScale Labs',
    previousCompanies: ['PhonePe', 'Swiggy'],
    education: 'B.Tech Computer Science, NIT Surathkal',
    phone: '+91 94250 88712',
    email: 'arjun.rao@example.com',
    stage: 'Interview',
    bookmarked: true,
    verified: {
      identity: true,
      phone: true,
      email: true,
      experience: true,
      education: false,
    },
    notes: ['Passed initial screening call with strong systems knowledge', 'Technical round scheduled for Thursday at 3 PM'],
  },
  {
    id: 'cand-3',
    name: 'Priya Nair',
    role: 'Senior Data Analyst',
    department: 'Data',
    location: 'Bhopal, MP',
    experienceYears: 6,
    skills: ['SQL', 'Python', 'Tableau', 'A/B Testing', 'Snowflake', 'dbt'],
    matchScore: 96,
    salaryExpected: '₹16,00,000',
    avatarBg: '#1F8A5D',
    bio: 'Analytical problem solver with strong background in user retention models, pipeline funnel analysis, and automated executive reporting.',
    appliedDate: '3 days ago',
    currentCompany: 'FinMetrics Corp',
    previousCompanies: ['Flipkart', 'Mu Sigma'],
    education: 'M.Sc Statistics, Delhi University',
    phone: '+91 98930 15432',
    email: 'priya.nair@example.com',
    stage: 'Screening',
    bookmarked: true,
    verified: {
      identity: true,
      phone: true,
      email: true,
      experience: true,
      education: true,
    },
    notes: ['Candidate of the week! Top match for analytics role.', 'Completed verification check seamlessly.'],
  },
  {
    id: 'cand-4',
    name: 'Leo Fischer',
    role: 'Growth Marketing Lead',
    department: 'Marketing',
    location: 'Indore, MP',
    experienceYears: 5,
    skills: ['SEO', 'Analytics', 'Paid Search', 'Conversion Optimization', 'HubSpot'],
    matchScore: 88,
    salaryExpected: '₹15,00,000',
    avatarBg: '#5576B8',
    bio: 'Performance marketer specializing in B2B SaaS acquisition, CAC minimization, and organic search engine domination.',
    appliedDate: '4 days ago',
    currentCompany: 'Nexus Growth Co',
    previousCompanies: ['Zoho', 'Byju Enterprise'],
    education: 'MBA Marketing, IIM Indore',
    phone: '+91 97520 99401',
    email: 'leo.fischer@example.com',
    stage: 'Applied',
    bookmarked: false,
    verified: {
      identity: true,
      phone: true,
      email: true,
      experience: true,
      education: false,
    },
    notes: ['Strong case studies in SaaS growth.', 'Waiting on recruiter review.'],
  },
  {
    id: 'cand-5',
    name: 'Sofia Alvarez',
    role: 'Frontend Architect',
    department: 'Engineering',
    location: 'Remote',
    experienceYears: 7,
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Next.js', 'Web Vitals'],
    matchScore: 91,
    salaryExpected: '₹26,00,000',
    avatarBg: '#6E5B9A',
    bio: 'Frontend enthusiast obsessed with 60fps render budgets, accessibility, and micro-frontend component architectures.',
    appliedDate: '5 days ago',
    currentCompany: 'CloudNative Inc',
    previousCompanies: ['CleverTap', 'Cognizant'],
    education: 'B.E Information Technology, Pune University',
    phone: '+91 99260 77319',
    email: 'sofia.alvarez@example.com',
    stage: 'Selected',
    bookmarked: true,
    verified: {
      identity: true,
      phone: true,
      email: true,
      experience: true,
      education: true,
    },
    notes: ['Excellent performance during live coding round', 'Final offer letter in preparation'],
  },
  {
    id: 'cand-6',
    name: 'Daniel Okafor',
    role: 'QA Automation Lead',
    department: 'Engineering',
    location: 'Pune, MH',
    experienceYears: 4,
    skills: ['Selenium', 'Jest', 'Playwright', 'API Automation', 'k6'],
    matchScore: 85,
    salaryExpected: '₹14,00,000',
    avatarBg: '#B85C68',
    bio: 'Detail-oriented test engineer experienced in continuous integration pipelines, contract testing, and regression suite optimization.',
    appliedDate: '6 days ago',
    currentCompany: 'Qualitas Global',
    previousCompanies: ['Infosys Labs'],
    education: 'B.Tech IT, SRM University',
    phone: '+91 94060 22189',
    email: 'daniel.okafor@example.com',
    stage: 'Applied',
    bookmarked: false,
    verified: {
      identity: true,
      phone: true,
      email: true,
      experience: false,
      education: true,
    },
    notes: ['Good experience with Playwright and GitHub Actions.'],
  },
  {
    id: 'cand-7',
    name: 'Wei Zhang',
    role: 'Staff Infrastructure Engineer',
    department: 'Infrastructure',
    location: 'Bengaluru, KA',
    experienceYears: 8,
    skills: ['Kubernetes', 'Terraform', 'AWS', 'Security', 'Grafana'],
    matchScore: 95,
    salaryExpected: '₹30,00,000',
    avatarBg: '#4D3D79',
    bio: 'Site reliability engineer passionate about zero-downtime canary rollouts, multi-region database failovers, and cost telemetry.',
    appliedDate: '1 week ago',
    currentCompany: 'Stripe Partners',
    previousCompanies: ['ThoughtWorks', 'Wipro Digital'],
    education: 'M.Tech Systems Engineering, IIT Madras',
    phone: '+91 91790 66345',
    email: 'wei.zhang@example.com',
    stage: 'Hired',
    bookmarked: true,
    verified: {
      identity: true,
      phone: true,
      email: true,
      experience: true,
      education: true,
    },
    notes: ['Offer accepted! Starting on the 1st of next month.', 'Background check 100% cleared.'],
  },
  {
    id: 'cand-8',
    name: 'Emma Larsen',
    role: 'Lead UX Researcher',
    department: 'Design',
    location: 'Remote',
    experienceYears: 5,
    skills: ['User Interviews', 'Usability Testing', 'Card Sorting', 'Information Architecture'],
    matchScore: 89,
    salaryExpected: '₹17,00,000',
    avatarBg: '#5F8A72',
    bio: 'Dedicated researcher turning qualitative behavioral observations into quantitative design impact metrics for hiring products.',
    appliedDate: '1 week ago',
    currentCompany: 'InsightPath',
    previousCompanies: ['MakeMyTrip', 'Fractal Analytics'],
    education: 'M.Sc Cognitive Psychology',
    phone: '+91 93010 44598',
    email: 'emma.larsen@example.com',
    stage: 'Applied',
    bookmarked: false,
    verified: {
      identity: true,
      phone: true,
      email: true,
      experience: true,
      education: true,
    },
    notes: ['Portfolio of user journey mapping and heuristics review looks solid.'],
  },
  {
    id: 'cand-9',
    name: 'Rahul Verma',
    role: 'Full-Stack Developer',
    department: 'Engineering',
    location: 'Bhopal, MP',
    experienceYears: 4,
    skills: ['React', 'Node.js', 'PostgreSQL', 'Express', 'Tailwind'],
    matchScore: 87,
    salaryExpected: '₹13,50,000',
    avatarBg: '#C58A3A',
    bio: 'Speed-focused product engineer skilled at taking mockups to live production features with clean TypeScript code.',
    appliedDate: '1 week ago',
    currentCompany: 'TechSpire Solutions',
    previousCompanies: ['TCS Innovation Labs'],
    education: 'B.E Computer Science, RGPV Bhopal',
    phone: '+91 98270 33811',
    email: 'rahul.verma@example.com',
    stage: 'Screening',
    bookmarked: false,
    verified: {
      identity: true,
      phone: true,
      email: true,
      experience: true,
      education: false,
    },
    notes: ['Local candidate in Bhopal. Open for hybrid office presence.'],
  },
  {
    id: 'cand-10',
    name: 'Hana Kobayashi',
    role: 'Senior Product Manager',
    department: 'Product',
    location: 'Bengaluru, KA',
    experienceYears: 6,
    skills: ['Roadmapping', 'Agile Sprints', 'SQL', 'PRDs', 'Recruiting Tech'],
    matchScore: 93,
    salaryExpected: '₹25,00,000',
    avatarBg: '#322554',
    bio: 'Outcome-oriented PM who shipped 0-to-1 ATS pipelines and automated screening algorithms across multi-sided marketplaces.',
    appliedDate: '2 weeks ago',
    currentCompany: 'HireCraft Global',
    previousCompanies: ['Ola', 'Urban Company'],
    education: 'B.Tech + MBA, IIT Bombay',
    phone: '+91 99810 55290',
    email: 'hana.kobayashi@example.com',
    stage: 'Applied',
    bookmarked: true,
    verified: {
      identity: true,
      phone: true,
      email: true,
      experience: true,
      education: true,
    },
    notes: ['Very impressed with her metrics on reducing time-to-hire by 42%.'],
  },
  {
    id: 'cand-11',
    name: 'Noah Bennett',
    role: 'Mobile Engineer (React Native)',
    department: 'Engineering',
    location: 'Hyderabad, TS',
    experienceYears: 4,
    skills: ['React Native', 'iOS Swift', 'Android Kotlin', 'Redux', 'Push Notifications'],
    matchScore: 84,
    salaryExpected: '₹16,00,000',
    avatarBg: '#6E5B9A',
    bio: 'Mobile craftsman specializing in smooth gestures, offline-first data sync, and instant push notifications for candidate alerts.',
    appliedDate: '2 weeks ago',
    currentCompany: 'AppCraft Labs',
    previousCompanies: ['Swiggy Delivery Tech'],
    education: 'B.Tech IT, Osmania University',
    phone: '+91 94240 11984',
    email: 'noah.bennett@example.com',
    stage: 'Applied',
    bookmarked: false,
    verified: {
      identity: true,
      phone: true,
      email: true,
      experience: false,
      education: true,
    },
    notes: ['Strong mobile UI samples in his GitHub.'],
  },
  {
    id: 'cand-12',
    name: 'Ananya Iyer',
    role: 'Technical Recruiter',
    department: 'People',
    location: 'Bengaluru, KA',
    experienceYears: 5,
    skills: ['Executive Search', 'LinkedIn Recruiter', 'Sourcing', 'ATS Optimization'],
    matchScore: 90,
    salaryExpected: '₹14,00,000',
    avatarBg: '#1F8A5D',
    bio: 'Senior talent partner with extensive networks in tech, data science, and design across high-growth startups.',
    appliedDate: '2 weeks ago',
    currentCompany: 'TalentPeak',
    previousCompanies: ['Razorpay', 'Randstad'],
    education: 'MBA Human Resources, Christ University',
    phone: '+91 97550 88204',
    email: 'ananya.iyer@example.com',
    stage: 'Interview',
    bookmarked: false,
    verified: {
      identity: true,
      phone: true,
      email: true,
      experience: true,
      education: true,
    },
    notes: ['Candidate culture match interview scheduled for Friday.'],
  },
];

export const INITIAL_INTERVIEWS: Interview[] = [
  {
    id: 'int-1',
    candidateId: 'cand-2',
    candidateName: 'Arjun Rao',
    candidateRole: 'Senior Backend Engineer',
    date: '2026-09-24',
    time: '03:00 PM - 04:00 PM',
    format: 'Google Meet',
    interviewer: 'Bhavuk Deshmukh & Tech Lead',
    link: 'https://meet.google.com/vrh-eng-tech',
    notes: 'System design deep dive: distributed cache invalidation & PostgreSQL write scalability.',
    status: 'scheduled',
  },
  {
    id: 'int-2',
    candidateId: 'cand-12',
    candidateName: 'Ananya Iyer',
    candidateRole: 'Technical Recruiter',
    date: '2026-09-25',
    time: '11:30 AM - 12:15 PM',
    format: 'Google Meet',
    interviewer: 'Bhavuk Deshmukh',
    link: 'https://meet.google.com/vrh-ppl-cul',
    notes: 'Values & culture interview. Discuss candidate sourcing pipelines and recruitment automation.',
    status: 'scheduled',
  },
  {
    id: 'int-3',
    candidateId: 'cand-1',
    candidateName: 'Maya Chen',
    candidateRole: 'Senior Product Designer',
    date: '2026-09-26',
    time: '02:00 PM - 03:00 PM',
    format: 'In-person',
    interviewer: 'Bhavuk Deshmukh & Head of Product',
    link: 'Verihire HQ, Arera Colony, Bhopal',
    notes: 'Design portfolio walkthrough & collaborative whiteboarding challenge.',
    status: 'scheduled',
  },
];

export const INITIAL_THREADS: MessageThread[] = [
  {
    id: 'thread-1',
    candidateId: 'cand-1',
    candidateName: 'Maya Chen',
    candidateRole: 'Senior Product Designer',
    candidateAvatarBg: '#42326E',
    lastMessage: 'Thank you Bhavuk! I look forward to our conversation next Tuesday.',
    lastMessageTime: '10:45 AM',
    unread: false,
    messages: [
      {
        id: 'm1',
        sender: 'recruiter',
        text: 'Hi Maya, your portfolio on complex dashboard systems really stood out to our hiring team. We would love to invite you for an in-depth conversation.',
        time: 'Yesterday 04:30 PM',
      },
      {
        id: 'm2',
        sender: 'candidate',
        text: 'Hello Bhavuk! Thank you so much for reaching out. I have been following Verihire and love the focus on verified talent. Next Tuesday afternoon works great for me.',
        time: 'Yesterday 05:15 PM',
      },
      {
        id: 'm3',
        sender: 'recruiter',
        text: 'Wonderful, I have scheduled our portfolio session for Tuesday at 2:00 PM. Looking forward to meeting you!',
        time: 'Today 10:15 AM',
      },
      {
        id: 'm4',
        sender: 'candidate',
        text: 'Thank you Bhavuk! I look forward to our conversation next Tuesday.',
        time: '10:45 AM',
      },
    ],
  },
  {
    id: 'thread-2',
    candidateId: 'cand-2',
    candidateName: 'Arjun Rao',
    candidateRole: 'Senior Backend Engineer',
    candidateAvatarBg: '#B9812C',
    lastMessage: 'Got the Google Meet invite, thanks! See you Thursday.',
    lastMessageTime: 'Yesterday',
    unread: true,
    messages: [
      {
        id: 'm21',
        sender: 'recruiter',
        text: 'Hi Arjun, thanks for taking the initial screening call today. The team was impressed by your PostgreSQL optimization work.',
        time: 'Yesterday 02:00 PM',
      },
      {
        id: 'm22',
        sender: 'recruiter',
        text: 'We have dispatched the calendar invite for your System Design interview on Thursday at 3 PM.',
        time: 'Yesterday 02:05 PM',
      },
      {
        id: 'm23',
        sender: 'candidate',
        text: 'Got the Google Meet invite, thanks! See you Thursday.',
        time: 'Yesterday 02:40 PM',
      },
    ],
  },
  {
    id: 'thread-3',
    candidateId: 'cand-3',
    candidateName: 'Priya Nair',
    candidateRole: 'Senior Data Analyst',
    candidateAvatarBg: '#1F8A5D',
    lastMessage: 'Hello Bhavuk, I have shared my case study presentation deck.',
    lastMessageTime: 'Sep 20',
    unread: false,
    messages: [
      {
        id: 'm31',
        sender: 'recruiter',
        text: 'Hello Priya, your credentials and identity have been verified on Verihire. We would like to review your data pipeline project.',
        time: 'Sep 19 11:00 AM',
      },
      {
        id: 'm32',
        sender: 'candidate',
        text: 'Hello Bhavuk, I have shared my case study presentation deck. Let me know if you need any additional SQL metrics!',
        time: 'Sep 20 09:20 AM',
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'New application received',
    body: 'Maya Chen applied for Senior Product Designer with 94% verified skill match.',
    time: '2 hours ago',
    type: 'application',
    read: false,
    linkRoute: 'dashboard',
  },
  {
    id: 'notif-2',
    title: 'Identity verification approved',
    body: 'Priya Nair completed Gov ID & Work History verification successfully.',
    time: '5 hours ago',
    type: 'verification',
    read: false,
    linkRoute: 'candidates',
  },
  {
    id: 'notif-3',
    title: 'Interview confirmed',
    body: 'Arjun Rao accepted Google Meet interview for Senior Backend Engineer on Thursday.',
    time: '1 day ago',
    type: 'interview',
    read: true,
    linkRoute: 'interviews',
  },
  {
    id: 'notif-4',
    title: 'Weekly recruitment summary',
    body: '18 active jobs generated 124 new candidate profiles this week (+18.4%).',
    time: '2 days ago',
    type: 'system',
    read: true,
    linkRoute: 'analytics',
  },
];

export const INITIAL_COMPANY: CompanyProfile = {
  name: 'Verihire Recruiting Corp',
  tagline: 'Precision recruitment with verified talent credentials',
  industry: 'Human Resources & Talent Intelligence Software',
  headquarters: 'Bhopal, Madhya Pradesh, India',
  website: 'https://verihire.example.com',
  teamSize: '50-150 employees',
  foundedYear: '2023',
  about: 'Verihire is an enterprise talent acquisition ecosystem that verifies candidate identity, education, and past tenure before they land on recruiter dashboards, drastically reducing screening time from weeks to 48 hours.',
  perks: [
    'Comprehensive Family Health Cover',
    '₹50,000 Annual Learning & Conference Budget',
    'Flexible Hybrid & Remote Work Policies',
    'Top-Tier MacBook Pro / Linux Workstation Setup',
    'Transparent ESOP & Performance Incentive Pool',
    'Generous 28-day Paid Time Off & Wellness Days',
  ],
};

// Storage helper functions
const STORAGE_KEYS = {
  JOBS: 'verihire_jobs_v1',
  CANDIDATES: 'verihire_candidates_v1',
  INTERVIEWS: 'verihire_interviews_v1',
  THREADS: 'verihire_threads_v1',
  NOTIFICATIONS: 'verihire_notifications_v1',
  COMPANY: 'verihire_company_v1',
};

export function loadStoredData<T>(key: string, defaultValue: T): T {
  try {
    const raw = localStorage.getItem(key);
    if (!raw) return defaultValue;
    return JSON.parse(raw) as T;
  } catch (e) {
    console.warn(`Error reading ${key} from storage:`, e);
    return defaultValue;
  }
}

export function saveStoredData<T>(key: string, data: T): void {
  try {
    localStorage.setItem(key, JSON.stringify(data));
  } catch (e) {
    console.warn(`Error saving ${key} to storage:`, e);
  }
}

export { STORAGE_KEYS };
